
export type VersionGroupValue =
    "red-blue"
    | "yellow"
    | "gold-silver"
    | "crystal"
    | "ruby-sapphire"
    | "emerald"
    | "firered-leafgreen"
    | "diamond-pearl"
    | "platinum"
    | "heartgold-soulsilver"
    | "black-white"
    | "colosseum"
    | "xd"
    | "black-2-white-2"
    | "x-y"
    | "omega-ruby-alpha-sapphire"
    | "sun-moon"
    | "ultra-sun-ultra-moon"
    | "lets-go-pikachu-lets-go-eevee"
    | "sword-shield"
    | "the-isle-of-armor"
    | "the-crown-tundra"
    | "brilliant-diamond-and-shining-pearl"
    | "legends-arceus"
    | "scarlet-violet"
    | "the-teal-mask"
    | "the-indigo-disk";

export type MoveLearnMethodValue =
    "level-up"
    | "egg"
    | "tutor"
    | "machine"
    | "stadium-surfing-pikachu"
    | "light-ball-egg"
    | "colosseum-purification"
    | "xd-shadow"
    | "xd-purification"
    | "form-change"
    | "zygarde-cube";